### ISSUE TITLE
Build behind by one?

### ISSUE THREAD

**Issue by chtinahow** [chtinahow/poll-theater#41]
server builds seem behind by one?

**Comment by JRJurman** [comment]
issue happens on mac

**Comment by JRJurman** [comment]
May have stopped since introducing `shell-executor`

**Comment by JRJurman** [comment]
This is definitely still occurring. 
On chrome OS, running `npm start` creates a dist folder, but then states that `dist/server.js` does not exist. 

This means that server.js doesn't exist by the time that `npm start` is called. This probably means that successive calls are falling back to the last built version of server.js
