### ISSUE TITLE
Unit Test Framework

### ISSUE THREAD

**Issue by JRJurman** [chtinahow/poll-theater#76]
Should figure out what technologies we will be using for this.

**Comment by JRJurman** [comment]
We should use supertest to test the server (already in PR #89). https://github.com/visionmedia/supertest
We should use chai-enzyme to test the components. https://github.com/producthunt/chai-enzyme

**Comment by JRJurman** [comment]
@chtinahow: does this sound good?

**Comment by chtinahow** [comment]
Sounds good to me
